version: "3.2"

services:
  server:
    build:
      context: ./
    environment:
      - DATABASE_DB=mongodb://mongo:27017/feira_livres
    depends_on:
      - mongo
    restart: always
    command: bash ./scripts/up_server.sh
    ports:
      - "9000:9000"
    volumes:
      - ./:/src/
  
  test:
    build:
      context: ./
    environment:
      - ENVIRONMENT:test
      - DATABASE_DB=mongodb://mongo:27017/feira_livres_teste
    depends_on:
      - mongo
    restart: always
    command: bash ./scripts/run_test.sh
    ports:
      - "9000:9000"
    volumes:
      - ./:/src/

  mongo:
    image: mongo:4.2.7-bionic
    hostname: mongo
    ports:
      - 27017:27017
    command: mongod
    expose:
      - 27017
